# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗ 
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║
# ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ 
# -------------------------------------------------------------------

source = ~/.config/hypr/import/lookfeel.conf
source = ~/.config/hypr/import/monitors.conf
source = ~/.config/hypr/import/apps.conf
source = ~/.config/hypr/import/keybinds.conf
source = ~/.config/hypr/import/input.conf
source = ~/.config/hypr/import/windowrule.conf
source = ~/.config/hypr/import/variable.conf
