#  █████╗ ██████╗ ██████╗ ███████╗
# ██╔══██╗██╔══██╗██╔══██╗██╔════╝
# ███████║██████╔╝██████╔╝███████╗
# ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║
# ██║  ██║██║     ██║     ███████║
# ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝
#----------------------------------

# apps
$terminal = kitty
$fileManager = thunar
$menu = wofi --show drun
$browser = firefox

# autostart apps
exec-once = hyprctl setcursor Adwaita 24
exec-once = waybar &
exec-once = swww-daemon &
exec-once = swww img /home/bawir/Pictures/wallpapers/wall1.png
